In [9]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/1000-cameras-dataset/camera_dataset.csv


# Import Dataset

In [10]:
dataset = pd.read_csv('/kaggle/input/1000-cameras-dataset/camera_dataset.csv')
dataset.head()

Model  Release date  Max resolution  Low resolution  \
0        Agfa ePhoto 1280          1997          1024.0           640.0   
1        Agfa ePhoto 1680          1998          1280.0           640.0   
2        Agfa ePhoto CL18          2000           640.0             0.0   
3        Agfa ePhoto CL30          1999          1152.0           640.0   
4  Agfa ePhoto CL30 Clik!          1999          1152.0           640.0   

   Effective pixels  Zoom wide (W)  Zoom tele (T)  Normal focus range  \
0               0.0           38.0          114.0                70.0   
1               1.0           38.0          114.0                50.0   
2               0.0           45.0           45.0                 0.0   
3               0.0           35.0           35.0                 0.0   
4               0.0           43.0           43.0                50.0   

   Macro focus range  Storage included  Weight (inc. batteries)  Dimensions  \
0               40.0               4.0                    420.0        95.0   
1                0.0               4.0                    420.0       158.0   
2                0.0               2.0                      0.0         0.0   
3                0.0               4.0                      0.0         0.0   
4                0.0              40.0                    300.0       128.0   

    Price  
0   179.0  
1   179.0  
2   179.0  
3   269.0  
4  1299.0

In [12]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [14]:
print(X.shape)

(1038, 11)


# Taking care of missing data

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
print(X)

[[1.997e+03 1.024e+03 6.400e+02 ... 4.000e+00 4.200e+02 9.500e+01]
 [1.998e+03 1.280e+03 6.400e+02 ... 4.000e+00 4.200e+02 1.580e+02]
 [2.000e+03 6.400e+02 0.000e+00 ... 2.000e+00 0.000e+00 0.000e+00]
 ...
 [2.001e+03 2.048e+03 1.024e+03 ... 8.000e+00 3.400e+02 1.070e+02]
 [2.001e+03 2.400e+03 1.200e+03 ... 1.600e+01 3.400e+02 1.070e+02]
 [2.002e+03 1.600e+03 8.000e+02 ... 8.000e+00 1.800e+02 8.600e+01]]


# Split Data Into Training Set and Test Set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)


# Train Model With Multiple Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = lin_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 421.52  129.  ]
 [ 541.4   429.  ]
 [ 371.73  229.  ]
 [ 297.35  169.  ]
 [ 240.65  179.  ]
 [ 549.98 1399.  ]
 [ 337.52  229.  ]
 [ 424.09  126.  ]
 [ 350.22   99.  ]
 [ 334.44  169.  ]
 [ 197.98  169.  ]
 [ 524.59 1499.  ]
 [ 542.86  499.  ]
 [1177.67 1699.  ]
 [ 343.75  279.  ]
 [ 240.93  269.  ]
 [ 387.89  299.  ]
 [ 404.31 1699.  ]
 [ 435.22  149.  ]
 [ 343.04  299.  ]
 [ 586.89  399.  ]
 [ 317.19  229.  ]
 [ 922.01  229.  ]
 [ 463.17  199.  ]
 [1220.81 1399.  ]
 [ 448.74  399.  ]
 [ 384.95  229.  ]
 [ 274.87  269.  ]
 [ 349.64  249.  ]
 [ 229.42  169.  ]
 [ 386.58  179.  ]
 [ 250.53  229.  ]
 [ 269.07  149.  ]
 [ 402.16  249.  ]
 [ 409.62  399.  ]
 [ 342.03  329.  ]
 [ 413.06   62.  ]
 [ 305.29  179.  ]
 [ 317.69  149.  ]
 [ 210.12  449.  ]
 [ 363.52  169.  ]
 [ 597.08  399.  ]
 [ 269.81  269.  ]
 [2055.72 4699.  ]
 [1147.38 1299.  ]
 [ 421.25  399.  ]
 [ 227.35  229.  ]
 [ 290.61  149.  ]
 [ 200.92  249.  ]
 [ 375.95  139.  ]
 [ 274.37 1499.  ]
 [ 377.88  329.  ]
 [ 298.06  1

# Train Model With Support Vector Regression

In [22]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(X, y)

SVR()

In [23]:
y_pred = svr_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 200.25  129.  ]
 [ 197.9   429.  ]
 [ 222.28  229.  ]
 [ 191.89  169.  ]
 [ 184.33  179.  ]
 [ 189.39 1399.  ]
 [ 207.49  229.  ]
 [ 213.97  126.  ]
 [ 209.51   99.  ]
 [ 231.46  169.  ]
 [ 216.63  169.  ]
 [ 199.75 1499.  ]
 [ 230.42  499.  ]
 [ 234.98 1699.  ]
 [ 223.77  279.  ]
 [ 188.29  269.  ]
 [ 221.97  299.  ]
 [ 184.22 1699.  ]
 [ 222.6   149.  ]
 [ 209.35  299.  ]
 [ 224.51  399.  ]
 [ 188.56  229.  ]
 [ 228.43  229.  ]
 [ 222.54  199.  ]
 [ 199.87 1399.  ]
 [ 198.8   399.  ]
 [ 184.39  229.  ]
 [ 189.3   269.  ]
 [ 223.56  249.  ]
 [ 199.67  169.  ]
 [ 209.39  179.  ]
 [ 187.68  229.  ]
 [ 209.24  149.  ]
 [ 223.34  249.  ]
 [ 217.02  399.  ]
 [ 225.7   329.  ]
 [ 184.38   62.  ]
 [ 193.13  179.  ]
 [ 211.43  149.  ]
 [ 208.23  449.  ]
 [ 184.09  169.  ]
 [ 213.86  399.  ]
 [ 213.56  269.  ]
 [ 238.97 4699.  ]
 [ 225.96 1299.  ]
 [ 226.65  399.  ]
 [ 198.54  229.  ]
 [ 209.66  149.  ]
 [ 222.88  249.  ]
 [ 188.28  139.  ]
 [ 211.23 1499.  ]
 [ 221.74  329.  ]
 [ 200.69  1

# Train Model With Decision Tree Regression

In [25]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state = 0)
dec_tree_reg.fit(X, y)

DecisionTreeRegressor(random_state=0)

In [32]:
dec_tree_pred = dec_tree_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((dec_tree_pred.reshape(len(dec_tree_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 129.  129.]
 [ 429.  429.]
 [ 229.  229.]
 [ 169.  169.]
 [ 179.  179.]
 [1399. 1399.]
 [ 229.  229.]
 [ 126.  126.]
 [  99.   99.]
 [ 169.  169.]
 [ 169.  169.]
 [1499. 1499.]
 [ 499.  499.]
 [1699. 1699.]
 [ 279.  279.]
 [ 269.  269.]
 [ 299.  299.]
 [1699. 1699.]
 [ 149.  149.]
 [ 299.  299.]
 [ 399.  399.]
 [ 229.  229.]
 [ 229.  229.]
 [ 199.  199.]
 [1399. 1399.]
 [ 399.  399.]
 [ 229.  229.]
 [ 269.  269.]
 [ 249.  249.]
 [ 169.  169.]
 [ 179.  179.]
 [ 229.  229.]
 [ 149.  149.]
 [ 249.  249.]
 [ 399.  399.]
 [ 329.  329.]
 [  62.   62.]
 [ 179.  179.]
 [ 149.  149.]
 [ 449.  449.]
 [ 169.  169.]
 [ 399.  399.]
 [ 269.  269.]
 [4699. 4699.]
 [1299. 1299.]
 [ 399.  399.]
 [ 229.  229.]
 [ 149.  149.]
 [ 249.  249.]
 [ 139.  139.]
 [1499. 1499.]
 [ 329.  329.]
 [ 149.  149.]
 [ 179.  179.]
 [  19.   19.]
 [ 179.  179.]
 [ 199.  199.]
 [ 449.  449.]
 [ 229.  229.]
 [ 229.  229.]
 [1599. 1599.]
 [ 229.  229.]
 [ 199.  199.]
 [ 129.  129.]
 [ 149.  149.]
 [ 229.  229.]
 [ 399.  3

# Train Model With Random Forest Regression 

In [41]:
from sklearn.ensemble import RandomForestRegressor
rand_for_reg = RandomForestRegressor(n_estimators = len(dataset), random_state = 0)
rand_for_reg.fit(X, y)

RandomForestRegressor(n_estimators=1038, random_state=0)

In [42]:
rand_for_pred = rand_for_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((rand_for_pred.reshape(len(rand_for_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 207.32  129.  ]
 [ 440.16  429.  ]
 [ 210.08  229.  ]
 [ 178.82  169.  ]
 [ 209.41  179.  ]
 [1266.66 1399.  ]
 [ 226.18  229.  ]
 [ 146.67  126.  ]
 [ 123.09   99.  ]
 [ 280.29  169.  ]
 [ 168.67  169.  ]
 [1476.9  1499.  ]
 [ 428.67  499.  ]
 [1660.35 1699.  ]
 [ 280.12  279.  ]
 [ 258.95  269.  ]
 [ 280.97  299.  ]
 [1454.05 1699.  ]
 [ 154.27  149.  ]
 [ 363.68  299.  ]
 [ 383.04  399.  ]
 [ 219.62  229.  ]
 [ 249.75  229.  ]
 [ 198.53  199.  ]
 [1211.84 1399.  ]
 [ 357.47  399.  ]
 [ 380.03  229.  ]
 [ 264.08  269.  ]
 [ 239.53  249.  ]
 [ 166.92  169.  ]
 [ 207.16  179.  ]
 [ 470.37  229.  ]
 [ 168.77  149.  ]
 [ 247.71  249.  ]
 [ 378.02  399.  ]
 [ 314.1   329.  ]
 [ 109.71   62.  ]
 [ 222.73  179.  ]
 [ 529.66  149.  ]
 [ 433.62  449.  ]
 [ 213.85  169.  ]
 [ 595.07  399.  ]
 [ 269.57  269.  ]
 [4777.13 4699.  ]
 [1169.08 1299.  ]
 [ 341.4   399.  ]
 [ 232.71  229.  ]
 [ 183.    149.  ]
 [ 237.76  249.  ]
 [ 166.63  139.  ]
 [1327.78 1499.  ]
 [ 311.24  329.  ]
 [ 172.53  1