In [9]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/1000-cameras-dataset/camera_dataset.csv


# Import Dataset

In [10]:
dataset = pd.read_csv('/kaggle/input/1000-cameras-dataset/camera_dataset.csv')
dataset.head()

Model  Release date  Max resolution  Low resolution  \
0        Agfa ePhoto 1280          1997          1024.0           640.0   
1        Agfa ePhoto 1680          1998          1280.0           640.0   
2        Agfa ePhoto CL18          2000           640.0             0.0   
3        Agfa ePhoto CL30          1999          1152.0           640.0   
4  Agfa ePhoto CL30 Clik!          1999          1152.0           640.0   

   Effective pixels  Zoom wide (W)  Zoom tele (T)  Normal focus range  \
0               0.0           38.0          114.0                70.0   
1               1.0           38.0          114.0                50.0   
2               0.0           45.0           45.0                 0.0   
3               0.0           35.0           35.0                 0.0   
4               0.0           43.0           43.0                50.0   

   Macro focus range  Storage included  Weight (inc. batteries)  Dimensions  \
0               40.0               4.0                    420.0        95.0   
1                0.0               4.0                    420.0       158.0   
2                0.0               2.0                      0.0         0.0   
3                0.0               4.0                      0.0         0.0   
4                0.0              40.0                    300.0       128.0   

    Price  
0   179.0  
1   179.0  
2   179.0  
3   269.0  
4  1299.0

In [12]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [14]:
print(X.shape)

(1038, 11)


# Taking care of missing data

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
print(X)

[[1.997e+03 1.024e+03 6.400e+02 ... 4.000e+00 4.200e+02 9.500e+01]
 [1.998e+03 1.280e+03 6.400e+02 ... 4.000e+00 4.200e+02 1.580e+02]
 [2.000e+03 6.400e+02 0.000e+00 ... 2.000e+00 0.000e+00 0.000e+00]
 ...
 [2.001e+03 2.048e+03 1.024e+03 ... 8.000e+00 3.400e+02 1.070e+02]
 [2.001e+03 2.400e+03 1.200e+03 ... 1.600e+01 3.400e+02 1.070e+02]
 [2.002e+03 1.600e+03 8.000e+02 ... 8.000e+00 1.800e+02 8.600e+01]]


# Split Data Into Training Set and Test Set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)


# Train Model With Multiple Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = lin_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 421.52  129.  ]
 [ 541.4   429.  ]
 [ 371.73  229.  ]
 [ 297.35  169.  ]
 [ 240.65  179.  ]
 [ 549.98 1399.  ]
 [ 337.52  229.  ]
 [ 424.09  126.  ]
 [ 350.22   99.  ]
 [ 334.44  169.  ]
 [ 197.98  169.  ]
 [ 524.59 1499.  ]
 [ 542.86  499.  ]
 [1177.67 1699.  ]
 [ 343.75  279.  ]
 [ 240.93  269.  ]
 [ 387.89  299.  ]
 [ 404.31 1699.  ]
 [ 435.22  149.  ]
 [ 343.04  299.  ]
 [ 586.89  399.  ]
 [ 317.19  229.  ]
 [ 922.01  229.  ]
 [ 463.17  199.  ]
 [1220.81 1399.  ]
 [ 448.74  399.  ]
 [ 384.95  229.  ]
 [ 274.87  269.  ]
 [ 349.64  249.  ]
 [ 229.42  169.  ]
 [ 386.58  179.  ]
 [ 250.53  229.  ]
 [ 269.07  149.  ]
 [ 402.16  249.  ]
 [ 409.62  399.  ]
 [ 342.03  329.  ]
 [ 413.06   62.  ]
 [ 305.29  179.  ]
 [ 317.69  149.  ]
 [ 210.12  449.  ]
 [ 363.52  169.  ]
 [ 597.08  399.  ]
 [ 269.81  269.  ]
 [2055.72 4699.  ]
 [1147.38 1299.  ]
 [ 421.25  399.  ]
 [ 227.35  229.  ]
 [ 290.61  149.  ]
 [ 200.92  249.  ]
 [ 375.95  139.  ]
 [ 274.37 1499.  ]
 [ 377.88  329.  ]
 [ 298.06  1

# Train Model With Support Vector Regression

In [43]:
from sklearn.svm import SVR
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(X_train, y_train)

SVR()

In [44]:
y_pred = svr_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 211.31  129.  ]
 [ 209.6   429.  ]
 [ 226.11  229.  ]
 [ 205.24  169.  ]
 [ 199.87  179.  ]
 [ 203.36 1399.  ]
 [ 216.34  229.  ]
 [ 220.71  126.  ]
 [ 217.7    99.  ]
 [ 231.49  169.  ]
 [ 222.19  169.  ]
 [ 210.97 1499.  ]
 [ 231.11  499.  ]
 [ 233.97 1699.  ]
 [ 227.    279.  ]
 [ 202.63  269.  ]
 [ 225.9   299.  ]
 [ 199.41 1699.  ]
 [ 226.32  149.  ]
 [ 217.59  299.  ]
 [ 227.5   399.  ]
 [ 202.83  229.  ]
 [ 229.93  229.  ]
 [ 226.28  199.  ]
 [ 210.79 1399.  ]
 [ 210.27  399.  ]
 [ 199.01  229.  ]
 [ 203.51  269.  ]
 [ 226.86  249.  ]
 [ 210.92  169.  ]
 [ 217.61  179.  ]
 [ 202.2   229.  ]
 [ 217.51  149.  ]
 [ 226.72  249.  ]
 [ 222.7   399.  ]
 [ 228.06  329.  ]
 [ 199.52   62.  ]
 [ 206.25  179.  ]
 [ 218.95  149.  ]
 [ 216.84  449.  ]
 [ 199.33  169.  ]
 [ 220.56  399.  ]
 [ 220.44  269.  ]
 [ 235.98 4699.  ]
 [ 228.36 1299.  ]
 [ 228.68  399.  ]
 [ 210.11  229.  ]
 [ 217.8   149.  ]
 [ 226.41  249.  ]
 [ 202.45  139.  ]
 [ 218.82 1499.  ]
 [ 225.75  329.  ]
 [ 211.61  1

# Train Model With Decision Tree Regression

In [45]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state = 0)
dec_tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [46]:
dec_tree_pred = dec_tree_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((dec_tree_pred.reshape(len(dec_tree_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 129.  129.]
 [ 429.  429.]
 [ 126.  229.]
 [ 169.  169.]
 [ 449.  179.]
 [1399. 1399.]
 [ 169.  229.]
 [ 249.  126.]
 [ 139.   99.]
 [1499.  169.]
 [ 169.  169.]
 [1499. 1499.]
 [ 429.  499.]
 [1699. 1699.]
 [ 229.  279.]
 [ 129.  269.]
 [ 126.  299.]
 [1699. 1699.]
 [  99.  149.]
 [1499.  299.]
 [ 399.  399.]
 [ 269.  229.]
 [1199.  229.]
 [ 229.  199.]
 [ 229. 1399.]
 [ 129.  399.]
 [ 229.  229.]
 [ 269.  269.]
 [ 149.  249.]
 [ 169.  169.]
 [ 169.  179.]
 [ 599.  229.]
 [ 149.  149.]
 [  99.  249.]
 [ 149.  399.]
 [ 269.  329.]
 [ 179.   62.]
 [ 799.  179.]
 [1499.  149.]
 [ 449.  449.]
 [  62.  169.]
 [1399.  399.]
 [ 269.  269.]
 [7999. 4699.]
 [1199. 1299.]
 [ 199.  399.]
 [ 229.  229.]
 [1699.  149.]
 [ 229.  249.]
 [ 139.  139.]
 [ 299. 1499.]
 [ 299.  329.]
 [ 229.  149.]
 [ 126.  179.]
 [1699.   19.]
 [ 179.  179.]
 [ 129.  199.]
 [ 449.  449.]
 [ 229.  229.]
 [1499.  229.]
 [1599. 1599.]
 [ 229.  229.]
 [ 509.  199.]
 [ 229.  129.]
 [ 149.  149.]
 [ 199.  229.]
 [ 179.  3

# Train Model With Random Forest Regression 

In [49]:
from sklearn.ensemble import RandomForestRegressor
rand_for_reg = RandomForestRegressor(n_estimators = 10, random_state = 0)
rand_for_reg.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [50]:
rand_for_pred = rand_for_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((rand_for_pred.reshape(len(rand_for_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 193.    129.  ]
 [ 570.    429.  ]
 [ 170.1   229.  ]
 [ 208.8   169.  ]
 [ 207.3   179.  ]
 [ 818.7  1399.  ]
 [ 216.7   229.  ]
 [ 194.    126.  ]
 [ 205.     99.  ]
 [ 594.5   169.  ]
 [ 168.    169.  ]
 [1202.   1499.  ]
 [ 233.    499.  ]
 [1549.   1699.  ]
 [ 221.    279.  ]
 [ 250.8   269.  ]
 [ 298.7   299.  ]
 [ 751.3  1699.  ]
 [ 170.7   149.  ]
 [ 733.    299.  ]
 [ 588.    399.  ]
 [ 314.3   229.  ]
 [ 860.    229.  ]
 [ 227.2   199.  ]
 [1184.   1399.  ]
 [ 249.    399.  ]
 [ 214.7   229.  ]
 [ 245.5   269.  ]
 [ 193.    249.  ]
 [ 174.7   169.  ]
 [ 324.3   179.  ]
 [ 870.    229.  ]
 [ 174.7   149.  ]
 [ 494.7   249.  ]
 [ 346.7   399.  ]
 [ 241.    329.  ]
 [ 161.3    62.  ]
 [ 194.8   179.  ]
 [ 873.    149.  ]
 [ 380.    449.  ]
 [ 231.    169.  ]
 [1522.    399.  ]
 [ 255.    269.  ]
 [4529.   4699.  ]
 [ 952.   1299.  ]
 [ 200.2   399.  ]
 [ 239.    229.  ]
 [ 240.    149.  ]
 [ 204.    249.  ]
 [ 340.3   139.  ]
 [1280.   1499.  ]
 [ 278.    329.  ]
 [ 295.    1